### ISSUE TITLE
API is throwing MaxRetryError 

### ISSUE THREAD

**Issue by tonygracious** [PreciselyData/PreciselyAPIsSDK-Python#2] opened 2024-05-07 03:52 UTC
I tried the the sample code mentioned in repo with my secret and key that I got from the https://developer.precisely.com/software-apis/apikeys webiste.

from com.precisely.apis.api.address_autocomplete_service_api import AddressAutocompleteServiceApi
from com.precisely.apis.exceptions import ApiException
def addressAutocompleteExample():
    api = AddressAutocompleteServiceApi()
    api.api_client.oAuthApiKey = "MyKey"
    api.api_client.oAuthSecret = "Mysecret"
    api.api_client.generateAndSetToken()
    try:
        response = api.search_v2("times sq", country="usa")
        print(response)
    except ApiException as e:
        print(e.body)
if __name__ == "_main_":
    addressAutocompleteExample()

However it gave the following error

name": "MaxRetryError",
	"message": "HTTPSConnectionPool(host='api.precisely.com', port=443): Max retries exceeded with url: /typeahead/v1/locations?country=usa&searchText=times+sq (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))",
	"stack": "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[0;31mSSLCertVerificationError\u001b[0m    

How can I solve this issue?

**Comment by murlimjha** [comment] 2024-05-08 11:41
Hi @tonygracious,
We have investigated this issue but unable to replicate the SSL issue, Please try one more time. Should the problem persist, kindly inform us.
Please note we are actively working to reproduce this issue on our end. Please use latest version of SDK ` pip install com.precisely.apis`.
Thank You.

**Comment by tonygracious** [comment] 2024-05-09 18:00
@murlimjha  Yes, I am still getting the error. 

SSLCertVerificationError                  Traceback (most recent call last)
File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:467, in HTTPConnectionPool._make_request(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)
    [466](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:466) try:
--> [467](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:467)     self._validate_conn(conn)
    [468](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:468) except (SocketTimeout, BaseSSLError) as e:

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:1099, in HTTPSConnectionPool._validate_conn(self, conn)
   [1098](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:1098) if conn.is_closed:
-> [1099](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:1099)     conn.connect()
   [1101](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:1101) # TODO revise this, see https://github.com/urllib3/urllib3/issues/2791

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:653, in HTTPSConnection.connect(self)
    [651](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:651) server_hostname_rm_dot = server_hostname.rstrip(".")
--> [653](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:653) sock_and_verified = _ssl_wrap_socket_and_match_hostname(
    [654](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:654)     sock=sock,
    [655](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:655)     cert_reqs=self.cert_reqs,
    [656](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:656)     ssl_version=self.ssl_version,
    [657](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:657)     ssl_minimum_version=self.ssl_minimum_version,
    [658](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:658)     ssl_maximum_version=self.ssl_maximum_version,
    [659](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:659)     ca_certs=self.ca_certs,
    [660](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:660)     ca_cert_dir=self.ca_cert_dir,
    [661](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:661)     ca_cert_data=self.ca_cert_data,
    [662](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:662)     cert_file=self.cert_file,
    [663](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connection.py:663)     key_file=self.key_file,
...
--> [515](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/retry.py:515)     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    [517](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/retry.py:517) log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)
    [519](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/util/retry.py:519) return new_retry

MaxRetryError: HTTPSConnectionPool(host='api.precisely.com', port=443): Max retries exceeded with url: /typeahead/v1/locations?country=usa&searchText=times+sq (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

**Comment by tonygracious** [comment] 2024-05-14 05:22
@murlimjha  Can you please tell me the status of this issue?

**Comment by murlimjha** [comment] 2024-05-14 07:28
Hi @tonygracious,
Unfortunately, we are still unable to reproduce the issue mentioned.
we are getting response 200 OK.
![image](https://github.com/PreciselyData/PreciselyAPIsSDK-Python/assets/65645948/2a738031-1378-4a33-b067-d2b5f6d18613)

You may try our rest endpoint service directly from your custom Python or any other code.
Please refer https://developer.precisely.com/apis/typeahead

If you need any more information, feel free to let us know.

Thanks

**Comment by murlimjha** [comment] 2024-06-06 11:22
Unable to reproduce this issue. closing the ticket.

**Closed as completed** 2024-06-06 11:22 UTC
